### ISSUE TITLE
1) Clear Project Description & Documentation

### ISSUE THREAD

**Issue by JonatanHyberg** [miwink/projinda-19#15]
Eran README fil är väldigt bra strukturerad, den har tydliga och logiska rubriker med bra innehåll under alla. 

Ni skulle kunna lägga till Authors som rubrik, där man snabbt kan se dom som arbetar.
För eran install så skulle det kunna vara lite tydligare enligt mig (men jag har ingen tidigare erfarenhet med Nodejs), kanske länka till nån video hur man installerar nodejs som ni vet är bra. 

Jag vet inte om det är viktigt men det är bara mastern som har den uppdaterade README filen.

**Comment by joloev** [comment]
Har lagt till Author. Har ändrat install-delen för att gör den tydligare och enklar att följa.
