### ISSUE TITLE
3) Use of Milestones and Features in Issue Tracker

### ISSUE THREAD

**Issue by JonatanHyberg** [miwink/projinda-19#17]
Ni har använt har använt både milestones och features bra i ert projekt. Allt är uppdelat i bra storlekar. 
Det enda jag tycker den saknar är långtidsplanering där framtida features kan stå. Kanske är onödigt men kan vara bra för att spara sina planer för projektet

**Comment by joloev** [comment]
Jag håller med dig, vi har lagt till en del efter detta.
