### ISSUE TITLE
5) Use of Branching and Pull Requests

### ISSUE THREAD

**Issue by JonatanHyberg** [miwink/projinda-19#19]
Ni har en tydlig uppdelning i era branches, men jag tycker att de är lite stora. Som richard sa så skulle man dela upp projektet och jobba i små bitar så man alltid har någon produkt även om projektet missar deadlinen. (Minimum Viable Product (MVP)). 

Ni har använt pull requests en gång under projektet gång, men jag ser inte det som nåt problem det är bara så ni har strukturerat ert projekt. Det löser sig när sätter ihop projectet.

**Comment by joloev** [comment]
Vi har tagit till oss denna feedback och delat upp våra branches i mycket mindre delar än innan. Nu har vi till exempel en branch för enskilda features. Det kommer definitivt bli fler pull requests allt eftersom.
